### ISSUE TITLE
Can I add images to questions?

### ISSUE THREAD

**Issue by XAPKIB** [Viber/build-a-bot-with-zero-coding#3]
Can I add images, emojis to questions or extras?

**Comment by ItamarM** [comment]
@XAPKIB well you have two options for images:
1) Use URLS to the image. It should render the image url and present it to the user.
2) I managed to fork this version and add support to new types of messages which includes rich_media/images/videos. I will try to get it it merged on the next version, but should be super easy for you to hack as well.

Regarding emojis. Be my guest!
