### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by ffaauusstt** [Viber/build-a-bot-with-zero-coding#4]
Hello @ItamarM. Please help me to understand:

1) How to teach this chat bot to make a **new row** in a table every time when the **same** respondent is repeatedly asking the questions of the bot?

2) How to make a function of start survey controllable by a respondent. For example, to make a default menu with Start keyboard (and other buttons for other scenarios)?

yours respectfully

**Comment by ItamarM** [comment]
Hi @ffaauusstt 

1. You can create your own version of the Spreadsheet and modify the [writeAnswer](https://github.com/Viber/build-a-bot-with-zero-coding/blob/master/script.gs#L166) method accordingly. You will also have to modify [getAnswerIndexForUser](https://github.com/Viber/build-a-bot-with-zero-coding/blob/master/script.gs#L132) as the logic might be different now. 
2. Not sure I understood your questions. But you can update the [sendWelcomeMessage](https://github.com/Viber/build-a-bot-with-zero-coding/blob/master/script.gs#L213) and send keyboard along.

Good luck.
